name: lattice-submodular-maximization

output:
  benchmarks: 'out/benchmarks'

selected:
  # set to 1 to print debug info, 0 otherwise
  verbose: 1

defaults:
  # integer-lattice submodular function to maximize
  - obj: 'demo_non_monotone'
  
  # specify the timeouts for the benchmarks
  - runtime: 'laptop'
